### ISSUE TITLE
explanation of new data elements

### ISSUE THREAD

**Issue by katieq1000** [GSA/marketplace-fedramp-gov#9]
The dates under Agency Review, PMO Review and Annual Assessment seem incorrect. I don't know if this is just sample data or real data.  Possibly i don't understand the meaning of each so an information tag would help.

- Agency Review: 01/28/2020
- PMO Review: 06/18/2020
- Annual Assessment: 06/18

Also Independent Assessor is blank but in order to correct, i have to refill out the whole Google docs form.  That seems excessive and risky.

This portion seems confusing.  the blocks at the top that have Authorizations and Reuse
![image](https://github.com/GSA/marketplace-fedramp-gov/assets/134447610/3430f3d4-16f3-435f-a336-fa68c25ff048)

This section is under the heading of "provided by CSP" but i'm not sure how we provide that:

Authorized Service

Service(s) Added in the last 90 days

Other Service(s)

**Comment by shivaalipour** [comment]
@katieq1000 Thank you for providing feedback. We have made several updates since May and wanted to see if your concerns were addressed. Data and dates have been updated, we have added helper text next to "Authorization Status" to help define the steps in the authorization process, and we have added updated helper text next to "Authorizations" and "Reuse" to better explain the terms. 

If information is still incorrect for a specific CSO, please let us know, and we can work with you to update the information.

**Comment by shivaalipour** [comment]
@katieq1000, please get in touch with us if you need further information or assistance with this issue. Otherwise, we are closing this issue out.
